### GroupBy and aggregate function

In [1]:
import pandas as pd

In [6]:
# reading the csv file
df_cars = pd.read_csv('Car_sales.csv')
df_cars = df_cars[['Manufacturer','Sales_in_thousands','Vehicle_type','Price_in_thousands','Engine_size','Horsepower','Fuel_capacity']]
df_cars.head()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4

## agg() function

In [9]:
# Calculate the sum of the columns.
df_cars.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [ ]:
# To calculate the mean of the dateset
df_cars.agg('mean') #Getting the typeError, as there are some string elements and columns in the dataset.  # new pandas version

TypeError: Could not convert ['AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuickBuickBuickBuickCadillacCadillacCadillacCadillacCadillacChevroletChevroletChevroletChevroletChevroletChevroletChevroletChevroletChevroletChryslerChryslerChryslerChryslerChryslerChryslerChryslerDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeFordFordFordFordFordFordFordFordFordFordFordHondaHondaHondaHondaHondaHyundaiHyundaiHyundaiInfinitiJaguarJeepJeepJeepLexusLexusLexusLexusLexusLexusLincolnLincolnLincolnMitsubishiMitsubishiMitsubishiMitsubishiMitsubishiMitsubishiMitsubishiMercuryMercuryMercuryMercuryMercuryMercuryMercedes-BMercedes-BMercedes-BMercedes-BMercedes-BMercedes-BMercedes-BMercedes-BMercedes-BNissanNissanNissanNissanNissanNissanNissanOldsmobileOldsmobileOldsmobileOldsmobileOldsmobileOldsmobilePlymouthPlymouthPlymouthPlymouthPontiacPontiacPontiacPontiacPontiacPontiacPorschePorschePorscheSaabSaabSaturnSaturnSaturnSaturnSaturnSubaruSubaruToyotaToyotaToyotaToyotaToyotaToyotaToyotaToyotaToyotaVolkswagenVolkswagenVolkswagenVolkswagenVolkswagenVolkswagenVolvoVolvoVolvoVolvoVolvoVolvo'
 'PassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerCarPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerCarPassengerPassengerPassengerPassengerPassengerPassengerCarCarCarCarCarCarPassengerPassengerPassengerPassengerPassengerPassengerCarCarCarCarCarPassengerPassengerCarCarCarPassengerPassengerPassengerPassengerPassengerCarCarCarPassengerPassengerPassengerPassengerCarCarPassengerPassengerCarPassengerPassengerPassengerPassengerPassengerCarCarPassengerPassengerPassengerPassengerCarCarPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerCarPassengerPassengerPassengerCarCarCarCarPassengerPassengerPassengerPassengerCarCarPassengerPassengerCarPassengerPassengerPassengerPassengerPassengerPassengerCarPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerCarPassengerPassengerPassengerPassengerCarCarCarCarCarPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassengerPassenger'] to numeric

In [ ]:
# To calculate the mean and count variables
df_cars.apply(['max','sum']) # as mean function wont work here.

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
max,Volvo,540.561,Passenger,85.500,8.0,450.0,32.0
sum,AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...,8320.698,PassengerPassengerPassengerPassengerPassengerP...,4245.567,477.5,29008.0,2800.5

In [14]:
# Different aggregates per columns: calculate th sum and mean in 'Sales in thousands' and sum & mean of 'Price_in_thousands'.

df_cars.agg({'Sales_in_thousands':['sum','max'],
             'Price_in_thousands':['min','sum']})  

# here we null values for price_in_thousands cause we never called the functions for those columns.

     Sales_in_thousands  Price_in_thousands
sum            8320.698            4245.567
max             540.561                 NaN
min                 NaN               9.235

### Aggregate over the columns

In [18]:
df_cars[['Sales_in_thousands','Price_in_thousands']].agg(['sum','mean'], axis=1)

        sum     mean
0    38.419  19.2095
1    67.784  33.8920
2    14.114  14.1140
3    50.588  25.2940
4    44.387  22.1935
..      ...      ...
152  27.945  13.9725
153  42.745  21.3725
154  46.331  23.1655
155  48.993  24.4965
156  54.969  27.4845

[157 rows x 2 columns]

In [20]:
# Aggregate different functions and rename the index of the resulting dataframe
df_cars.agg(x=('Price_in_thousands','sum'), y =('Sales_in_thousands','mean'))

   Price_in_thousands  Sales_in_thousands
x            4245.567                 NaN
y                 NaN           52.998076

### The split-apply-combine strategy

The Strategy helps us to group values in a dataframe. so we build categories and we can apply some aggre function. so, we can the values of these categories.

In [22]:
# split data into separate groups
df_cars['Vehicle_type'].value_counts() # we gonna split dataframe into the two categories.

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [25]:
# filtering the data
passenger_data = df_cars['Vehicle_type'] == 'Passenger'
car_data = df_cars['Vehicle_type'] == 'Car'
passenger_data

0      True
1      True
2      True
3      True
4      True
       ...
152    True
153    True
154    True
155    True
156    True
Name: Vehicle_type, Length: 157, dtype: bool

### apply an operation

In [ ]:
# filtered dataframe
df_cars[passenger_data] # we will get the other filtered dataframe by using car_data.

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [31]:
# applying an operation 
cars_average = df_cars[car_data]['Sales_in_thousands'].agg('mean')
passenger_average = df_cars[passenger_data]['Sales_in_thousands'].agg('mean')

In [33]:
#Combining the results
pd.DataFrame({'Vehicle_type':['Car','Passenger'],
              'Sales_in_thousands':[cars_average,passenger_average]})

  Vehicle_type  Sales_in_thousands
0          Car           80.622293
1    Passenger           43.234345