In [1]:
import pandas as pd

### Pandas Practice Exercises - Groupby & Aggregation

 Question 1 (Beginner) - nunique()
You have a DataFrame containing information about online orders. 

Find out how many unique customers, products, and cities are in the dataset.

In [3]:
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'customer': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Alice', 'Diana', 'Bob'],
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Mouse', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'city': ['NYC', 'LA', 'NYC', 'Chicago', 'LA', 'NYC', 'Boston', 'LA'],
    'amount': [1200, 25, 75, 25, 1200, 25, 300, 75]
})
orders

   order_id customer   product     city  amount
0       101    Alice    Laptop      NYC    1200
1       102      Bob     Mouse       LA      25
2       103    Alice  Keyboard      NYC      75
3       104  Charlie     Mouse  Chicago      25
4       105      Bob    Laptop       LA    1200
5       106    Alice     Mouse      NYC      25
6       107    Diana   Monitor   Boston     300
7       108      Bob  Keyboard       LA      75

In [11]:
orders.nunique()

order_id    8
customer    4
product     4
city        4
amount      4
dtype: int64

### Exercise 2: Basic agg()

Using the same orders DataFrame, calculate the total revenue (sum of amount), average 

order value (mean of amount), and total number of orders (count).

In [28]:
orders
print('Total Revenue:', orders['amount'].agg('sum'))
print(f'Mean', {orders['amount'].agg('mean')})
print('Count', orders['order_id'].count())

results = orders.drop(columns=['customer','product','city']).agg(['sum','mean','count'])['amount']
print(results)

Total Revenue: 2925
Mean {np.float64(365.625)}
Count 8
sum      2925.000
mean      365.625
count       8.000
Name: amount, dtype: float64

### Question 3 (Beginner) - Different aggregations per column

You have employee data. Calculate the sum and mean of 'salary', and the min and max of 

'age' in a single operation.

In [41]:
employees = pd.DataFrame({
    'name': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom'],
    'age': [28, 34, 45, 29, 38],
    'salary': [50000, 65000, 75000, 58000, 70000],
    'department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})
employees

    name  age  salary department
0   John   28   50000         IT
1  Sarah   34   65000         HR
2   Mike   45   75000         IT
3   Lisa   29   58000    Finance
4    Tom   38   70000         HR

In [43]:
employees.agg({
    'salary':['mean','sum'],
    'age':['min','max']
}).T

           mean       sum   min   max
salary  63600.0  318000.0   NaN   NaN
age         NaN       NaN  28.0  45.0

### Question 4 (Intermediate) - agg() with axis parameter

You have monthly sales data for 3 products. Calculate the total sales for each month (sum across products).

In [45]:
sales = pd.DataFrame({
    'Product_A': [100, 150, 120, 180],
    'Product_B': [200, 180, 210, 190],
    'Product_C': [150, 160, 140, 170]
})
sales.index = ['January', 'February', 'March', 'April']
sales

          Product_A  Product_B  Product_C
January         100        200        150
February        150        180        160
March           120        210        140
April           180        190        170

In [53]:

sales.agg({
    'January' : ['sum'],
    'February':['sum'],
    'March':['sum'],
    'April':['sum']
},axis=0)

     January  February  March  April
sum      450       490    470    540

### Question 5 (Beginner) - Basic groupby()

You have student exam scores. Group by 'subject' and calculate the average score for each subject.

In [57]:
scores = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
    'subject': ['Math', 'Math', 'Math', 'Science', 'Science', 'Science'],
    'score': [85, 78, 92, 88, 82, 95]
})
scores

   student  subject  score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     88
4      Bob  Science     82
5  Charlie  Science     95

In [63]:
scores.groupby('subject')['score'].agg('mean')

subject
Math       85.000000
Science    88.333333
Name: score, dtype: float64

### Question 6 (Intermediate) - groupby() with get_group()

You have sales data from different stores. First, group by 'store', then extract and display only the data for 'Store B'

In [65]:
sales_data = pd.DataFrame({
    'store': ['Store A', 'Store B', 'Store A', 'Store C', 'Store B', 'Store C', 'Store A'],
    'product': ['Widget', 'Gadget', 'Gadget', 'Widget', 'Widget', 'Gadget', 'Widget'],
    'sales': [100, 150, 120, 90, 200, 110, 130],
    'profit': [20, 45, 30, 15, 60, 25, 35]
})
sales_data

     store product  sales  profit
0  Store A  Widget    100      20
1  Store B  Gadget    150      45
2  Store A  Gadget    120      30
3  Store C  Widget     90      15
4  Store B  Widget    200      60
5  Store C  Gadget    110      25
6  Store A  Widget    130      35

In [69]:
sales_data.groupby('store').get_group('Store B')

     store product  sales  profit
1  Store B  Gadget    150      45
4  Store B  Widget    200      60

### Question 7 (Intermediate) - groupby() with multiple aggregations

You have product inventory data. Group by 'category' and find both the minimum and maximum price for each category in one operation.

In [70]:
inventory = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Headphones'],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories'],
    'price': [1200, 25, 75, 400, 80, 150],
    'stock': [15, 100, 50, 20, 45, 60]
})
inventory

      product     category  price  stock
0      Laptop  Electronics   1200     15
1       Mouse  Accessories     25    100
2    Keyboard  Accessories     75     50
3     Monitor  Electronics    400     20
4      Webcam  Accessories     80     45
5  Headphones  Accessories    150     60

In [75]:
inventory.groupby('category').agg(['min','max'])['price']

             min   max
category
Accessories   25   150
Electronics  400  1200

### Question 8 (Intermediate) - Named aggregations

You have restaurant orders. Group by 'meal_type' and calculate the total revenue (sum of price) and average order size (mean of quantity), giving clear names to these aggregations.

In [76]:
restaurant = pd.DataFrame({
    'order_id': [1, 2, 3, 4, 5, 6],
    'meal_type': ['Breakfast', 'Lunch', 'Breakfast', 'Dinner', 'Lunch', 'Dinner'],
    'price': [12.50, 25.00, 10.00, 35.00, 22.00, 40.00],
    'quantity': [1, 2, 1, 3, 2, 2]
})
restaurant

   order_id  meal_type  price  quantity
0         1  Breakfast   12.5         1
1         2      Lunch   25.0         2
2         3  Breakfast   10.0         1
3         4     Dinner   35.0         3
4         5      Lunch   22.0         2
5         6     Dinner   40.0         2

In [78]:
restaurant.groupby('meal_type').agg(
    total_revenue = ('price','sum'),
    order_size = ('quantity', 'mean')
)

           total_revenue  order_size
meal_type
Breakfast           22.5         1.0
Dinner              75.0         2.5
Lunch               47.0         2.0

### Question 9 (Intermediate) - Using apply() with lambda

You have monthly expenses in thousands. Group by 'category', calculate the sum, and then convert it to actual dollar amounts (multiply by 1000)

In [79]:
expenses = pd.DataFrame({
    'category': ['Housing', 'Food', 'Housing', 'Transport', 'Food', 'Transport'],
    'month': ['Jan', 'Jan', 'Feb', 'Jan', 'Feb', 'Feb'],
    'amount_thousands': [2.5, 0.8, 2.5, 0.5, 0.9, 0.6]
})
expenses

    category month  amount_thousands
0    Housing   Jan               2.5
1       Food   Jan               0.8
2    Housing   Feb               2.5
3  Transport   Jan               0.5
4       Food   Feb               0.9
5  Transport   Feb               0.6

In [81]:
expenses.groupby('category')['amount_thousands'].sum().apply(lambda x:x*1000 )

category
Food         1700.0
Housing      5000.0
Transport    1100.0
Name: amount_thousands, dtype: float64

### Question 10 (Advanced) - filter() with groupby

You have sales data for different salespersons. Filter and keep only those salespersons whose total sales exceed $500.

In [82]:
sales_team = pd.DataFrame({
    'salesperson': ['Tom', 'Jerry', 'Tom', 'Spike', 'Jerry', 'Tom', 'Spike'],
    'product': ['A', 'B', 'C', 'A', 'A', 'B', 'C'],
    'sales': [150, 200, 180, 120, 250, 170, 90]
})

sales_team

  salesperson product  sales
0         Tom       A    150
1       Jerry       B    200
2         Tom       C    180
3       Spike       A    120
4       Jerry       A    250
5         Tom       B    170
6       Spike       C     90

In [90]:
def q10(sales_team):
    return sales_team['sales'].sum() >= 500

sales_team.groupby('salesperson').filter(q10)

  salesperson product  sales
0         Tom       A    150
2         Tom       C    180
5         Tom       B    170