In [1]:
import pandas as pd

In [3]:


# Create a sample dataset
data = {
    'Store': ['North', 'North', 'North', 'South', 'South', 'South', 'East', 'East', 'West', 'West'],
    'Product': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Apple', 'Orange'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit'],
    'Units_Sold': [150, 200, 80, 120, 180, 95, 200, 150, 90, 110],
    'Price_Per_Unit': [1.5, 0.75, 2.0, 1.6, 0.80, 1.9, 1.4, 0.70, 1.55, 2.1],
    'Revenue': [225, 150, 160, 192, 144, 180.5, 280, 105, 139.5, 231]
}

df = pd.DataFrame(data)
print(df)

   Store Product Category  Units_Sold  Price_Per_Unit  Revenue
0  North   Apple    Fruit         150            1.50    225.0
1  North  Banana    Fruit         200            0.75    150.0
2  North  Orange    Fruit          80            2.00    160.0
3  South   Apple    Fruit         120            1.60    192.0
4  South  Banana    Fruit         180            0.80    144.0
5  South  Orange    Fruit          95            1.90    180.5
6   East   Apple    Fruit         200            1.40    280.0
7   East  Banana    Fruit         150            0.70    105.0
8   West   Apple    Fruit          90            1.55    139.5
9   West  Orange    Fruit         110            2.10    231.0

#### Exercise Set 1: Basic Aggregation with agg()
Exercise 1.1 - Single Aggregation
Task: Calculate the sum of all values in the Units_Sold column using agg().

In [4]:
df['Units_Sold'].agg('sum')

np.int64(1375)

Exercise 1.2 - Mean Calculation
Task: Calculate the mean of all numeric columns using agg().

In [20]:
df.iloc[:,-3:].agg('mean')

Units_Sold        137.50
Price_Per_Unit      1.43
Revenue           180.70
dtype: float64

Exercise 1.3 - Multiple Aggregations
Task: Calculate both the mean and count for all columns using agg().

In [8]:
df.iloc[:,-3:].agg(['count','mean'])

       Units_Sold  Price_Per_Unit  Revenue
count        10.0           10.00     10.0
mean        137.5            1.43    180.7

Exercise 1.4 - Different Aggregations per Column
Task: Calculate:

sum and max for Units_Sold

mean and min for Revenue

In [21]:
df.agg({
    'Units_Sold':['sum','mean'],
    'Revenue':['mean','min']
})

      Units_Sold  Revenue
sum       1375.0      NaN
mean       137.5    180.7
min          NaN    105.0

Exercise 1.5 - Row-wise Aggregation

Task: Calculate the sum of Units_Sold and Revenue for each row (across columns).

In [37]:
df[['Units_Sold','Revenue']].agg('sum',axis=1)

0    375.0
1    350.0
2    240.0
3    312.0
4    324.0
5    275.5
6    480.0
7    255.0
8    229.5
9    341.0
dtype: float64

### Exercise Set 2: GroupBy Basics

Exercise 2.1 - Simple GroupBy

Task: Group the data by Store and calculate the mean of all numeric columns.

In [38]:
df

   Store Product Category  Units_Sold  Price_Per_Unit  Revenue
0  North   Apple    Fruit         150            1.50    225.0
1  North  Banana    Fruit         200            0.75    150.0
2  North  Orange    Fruit          80            2.00    160.0
3  South   Apple    Fruit         120            1.60    192.0
4  South  Banana    Fruit         180            0.80    144.0
5  South  Orange    Fruit          95            1.90    180.5
6   East   Apple    Fruit         200            1.40    280.0
7   East  Banana    Fruit         150            0.70    105.0
8   West   Apple    Fruit          90            1.55    139.5
9   West  Orange    Fruit         110            2.10    231.0

In [40]:
df.iloc[:,-3:].groupby(df['Store']).agg('mean')

       Units_Sold  Price_Per_Unit     Revenue
Store
East   175.000000        1.050000  192.500000
North  143.333333        1.416667  178.333333
South  131.666667        1.433333  172.166667
West   100.000000        1.825000  185.250000

Exercise 2.2 - GroupBy with Sum

Task: Group by Product and calculate the total (sum) of Units_Sold for each product.

In [41]:
df.groupby('Product')['Units_Sold'].agg('sum')

Product
Apple     560
Banana    530
Orange    285
Name: Units_Sold, dtype: int64

Exercise 2.3 - Accessing Groups

Task: Create a groupby object, print all group keys, and get data for 'North' store only.

In [50]:
df.groupby('Store').get_group('North')

   Store Product Category  Units_Sold  Price_Per_Unit  Revenue
0  North   Apple    Fruit         150            1.50    225.0
1  North  Banana    Fruit         200            0.75    150.0
2  North  Orange    Fruit          80            2.00    160.0

Exercise 2.4 - GroupBy Count

Task: Group by Store and count how many products each store has.

In [52]:
df.groupby('Store').count()['Product']

Store
East     2
North    3
South    3
West     2
Name: Product, dtype: int64

Exercise 2.5 - Unique Values

Task: Find how many unique values exist in each column using nunique().

In [53]:
df.nunique()

Store              4
Product            3
Category           1
Units_Sold         8
Price_Per_Unit    10
Revenue           10
dtype: int64

### 📝 Exercise Set 3: GroupBy with agg()

Exercise 3.1 - Multiple Aggregations per Group

Task: Group by Store and find the min and max values for Units_Sold and Revenue.

In [55]:
df.groupby('Store').agg(['min','max'])[['Units_Sold','Revenue']]

      Units_Sold      Revenue
             min  max     min    max
Store
East         150  200   105.0  280.0
North         80  200   150.0  225.0
South         95  180   144.0  192.0
West          90  110   139.5  231.0

Exercise 3.2 - Named Aggregations

Task: Group by Product and calculate total units sold (name it total_units) and average revenue (name it avg_revenue).

In [58]:
df.groupby('Product').agg(total_units=('Units_Sold','sum'),avg_revenue=('Revenue','mean'))

         total_units  avg_revenue
Product
Apple            560      209.125
Banana           530      133.000
Orange           285      190.500

Exercise 3.3 - Complex Aggregation

Task: Group by Store and calculate sum of Units_Sold, mean of Price_Per_Unit, and max of Revenue.

In [62]:
df.groupby('Store').agg({
    'Units_Sold':'sum',
    'Price_Per_Unit':'mean',
    'Revenue':'max'
})

       Units_Sold  Price_Per_Unit  Revenue
Store
East          350        1.050000    280.0
North         430        1.416667    225.0
South         395        1.433333    192.0
West          200        1.825000    231.0

### 📝 Exercise Set 4: Lambda Functions with GroupBy

Exercise 4.1 - Simple Lambda

Task: Group by Store, sum the Revenue, then multiply all values by 100 (convert to cents).

In [64]:
df.groupby('Store')['Revenue'].sum().apply(lambda x: x*100 )

Store
East     38500.0
North    53500.0
South    51650.0
West     37050.0
Name: Revenue, dtype: float64

Exercise 4.2 - Subtract Group Mean

Task: Group by Product and subtract the mean Units_Sold from each value within the group.

In [65]:
df.groupby('Product')['Units_Sold'].apply(lambda x: x-x.mean())

Product
Apple    0    10.000000
         3   -20.000000
         6    60.000000
         8   -50.000000
Banana   1    23.333333
         4     3.333333
         7   -26.666667
Orange   2   -15.000000
         5     0.000000
         9    15.000000
Name: Units_Sold, dtype: float64

Exercise 4.3 - Custom Calculation (Range)

Task: Group by Store and calculate the range (max - min) of Revenue for each store.

In [76]:
df.groupby('Store')['Revenue'].apply(lambda x: x.max() - x.min())

Store
East     175.0
North     75.0
South     48.0
West      91.5
Name: Revenue, dtype: float64

### 📝 Exercise Set 5: Challenge Exercises

Task: Find which Store has the highest average Revenue

In [81]:
df.groupby('Store')['Revenue'].mean().idxmax()

'East'

Challenge 5.2 - Multiple Group Keys

Task: Group by both Store AND Product, then calculate the total Units_Sold.

In [83]:
df.groupby(['Store','Product'])['Units_Sold'].sum()

Store  Product
East   Apple      200
       Banana     150
North  Apple      150
       Banana     200
       Orange      80
South  Apple      120
       Banana     180
       Orange      95
West   Apple       90
       Orange     110
Name: Units_Sold, dtype: int64

Challenge 5.3 - Calculate Percentages

Task: Calculate what percentage of total revenue each store contributes.

In [93]:
total_revenue = df['Revenue'].sum()
#print(total_revenue)

df.groupby('Store')['Revenue'].sum().apply(lambda x: (x/total_revenue*100))

Store
East     21.306032
North    29.607084
South    28.583287
West     20.503597
Name: Revenue, dtype: float64