In [2]:
import pandas as pd

### Question 1 (Beginner) - loc[] for label-based selection

You have a DataFrame of students with their test scores. Use loc[] to select the data for students 'Alice' and 'Charlie', showing only their 'math_score' and 'science_score' columns.

In [3]:
import pandas as pd

students = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'math_score': [85, 78, 92, 88, 95],
    'science_score': [90, 82, 88, 91, 89],
    'english_score': [88, 85, 90, 87, 91]
})
students.set_index('name', inplace=True)
students

         math_score  science_score  english_score
name
Alice            85             90             88
Bob              78             82             85
Charlie          92             88             90
Diana            88             91             87
Eve              95             89             91

In [5]:
students.loc[['Alice','Charlie'],['math_score','english_score']]

         math_score  english_score
name
Alice            85             88
Charlie          92             90

### Question 2 (Beginner) - iloc[] for position-based selection

Using the same students DataFrame, select the first 3 rows and the last 2 columns using position-based indexing.

In [16]:
students.iloc[:2,1:]

       science_score  english_score
name
Alice             90             88
Bob               82             85

### Question 3 (Beginner) - sort_values()

You have employee data. Sort the employees by salary in descending order (highest to lowest).

In [17]:
employees = pd.DataFrame({
    'name': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom'],
    'department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'salary': [65000, 70000, 58000, 75000, 62000],
    'age': [28, 34, 45, 29, 38]
})
employees

    name department  salary  age
0   John         IT   65000   28
1  Sarah         HR   70000   34
2   Mike         IT   58000   45
3   Lisa    Finance   75000   29
4    Tom         HR   62000   38

In [25]:
employees.sort_values('salary', ascending=False)

    name department  salary  age
3   Lisa    Finance   75000   29
1  Sarah         HR   70000   34
0   John         IT   65000   28
4    Tom         HR   62000   38
2   Mike         IT   58000   45

In [24]:
employees[employees.duplicated('department',keep='last')]

    name department  salary  age
0   John         IT   65000   28
1  Sarah         HR   70000   34

### Question 4 (Intermediate) - sort_values() with multiple columns

You have sales data. Sort first by 'region' (alphabetically), then by 'sales' (highest to lowest) within each region.

In [26]:
sales = pd.DataFrame({
    'salesperson': ['Tom', 'Jerry', 'Mike', 'Sarah', 'Lisa', 'John'],
    'region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'sales': [15000, 22000, 18000, 19000, 21000, 17000]
})
sales

  salesperson region  sales
0         Tom   East  15000
1       Jerry   West  22000
2        Mike   East  18000
3       Sarah   West  19000
4        Lisa   East  21000
5        John   West  17000

In [32]:
sales_region = sales.sort_values('region')
print(sales_region)

sales_region.sort_values('sales', ascending=False)

  salesperson region  sales
0         Tom   East  15000
2        Mike   East  18000
4        Lisa   East  21000
1       Jerry   West  22000
3       Sarah   West  19000
5        John   West  17000

  salesperson region  sales
1       Jerry   West  22000
4        Lisa   East  21000
3       Sarah   West  19000
2        Mike   East  18000
5        John   West  17000
0         Tom   East  15000

### Question 5 (Beginner) - Boolean filtering

You have product data. Filter and show only products that are priced above $100.

In [3]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'USB Cable', 'Headphones'],
    'price': [1200, 25, 75, 400, 15, 150],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories'],
    'in_stock': [True, True, False, True, True, False]
})
products

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
1       Mouse     25  Accessories      True
2    Keyboard     75  Accessories     False
3     Monitor    400  Electronics      True
4   USB Cable     15  Accessories      True
5  Headphones    150  Accessories     False

In [39]:
products[products['price']>100]

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
3     Monitor    400  Electronics      True
5  Headphones    150  Accessories     False

### Question 6 (Intermediate) - Multiple conditions with boolean filtering

From the products DataFrame, find all products that are:

    In the 'Accessories' category AND
    
    Priced between $50 and $200 (inclusive) AND
    
    Currently in stock

In [4]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'USB Cable', 'Headphones', 'Webcam'],
    'price': [1200, 25, 75, 400, 15, 150, 80],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Accessories'],
    'in_stock': [True, True, False, True, True, True, True]
})

products

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
1       Mouse     25  Accessories      True
2    Keyboard     75  Accessories     False
3     Monitor    400  Electronics      True
4   USB Cable     15  Accessories      True
5  Headphones    150  Accessories      True
6      Webcam     80  Accessories      True

In [10]:
products[
    (products['category'] == 'Accessories') &
    (products['price'] > 50) &
    (products['price'] < 200) &
    (products['in_stock'] == True)
]

      product  price     category  in_stock
5  Headphones    150  Accessories      True
6      Webcam     80  Accessories      True

### Question 7 (Beginner) - fillna() to handle missing data

You have temperature readings with some missing values (NaN). Fill the missing values with the average temperature.

In [12]:
import numpy as np

temperatures = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami'],
    'temperature': [72, np.nan, 65, np.nan, 88, 82]
})
temperatures

          city  temperature
0     New York         72.0
1  Los Angeles          NaN
2      Chicago         65.0
3      Houston          NaN
4      Phoenix         88.0
5        Miami         82.0

In [13]:
avg_tmep =temperatures['temperature'].mean()
temperatures.fillna(avg_tmep)

          city  temperature
0     New York        72.00
1  Los Angeles        76.75
2      Chicago        65.00
3      Houston        76.75
4      Phoenix        88.00
5        Miami        82.00

### Question 8 (Beginner) - Creating new columns

You have sales data with quantity and unit price. Create a new column 'total_price' that calculates quantity × unit_price.

In [19]:
sales = pd.DataFrame({
    'product': ['Widget', 'Gadget', 'Doohickey', 'Thingamajig'],
    'quantity': [10, 5, 8, 12],
    'unit_price': [25.50, 40.00, 15.75, 30.00]
})

sales

       product  quantity  unit_price
0       Widget        10       25.50
1       Gadget         5       40.00
2    Doohickey         8       15.75
3  Thingamajig        12       30.00

In [21]:
sales['Total_price'] = sales['quantity'] * sales['unit_price']
sales

       product  quantity  unit_price  Total_price
0       Widget        10       25.50        255.0
1       Gadget         5       40.00        200.0
2    Doohickey         8       15.75        126.0
3  Thingamajig        12       30.00        360.0

### Question 9 (Intermediate) - value_counts()

You have customer feedback data. Count how many times each rating appears, show the results in descending order with percentages.

In [23]:
feedback = pd.DataFrame({
    'customer': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom', 'Emma', 'David', 'Anna', 'Chris', 'Julie'],
    'rating': [5, 4, 5, 3, 5, 4, 5, 2, 4, 5]
})
feedback

  customer  rating
0     John       5
1    Sarah       4
2     Mike       5
3     Lisa       3
4      Tom       5
5     Emma       4
6    David       5
7     Anna       2
8    Chris       4
9    Julie       5

In [34]:
print('Rating count:')
rating_count = feedback.value_counts('rating')
print(rating_count)

print('Rating Percentage:')

rating_percentage = feedback.value_counts('rating',normalize=True) * 100

print(rating_percentage)

print('Final Results:')
final_result = pd.DataFrame({
    'count' : rating_count,\
    'percentage': rating_percentage
})
print(final_result)

Rating count:
rating
5    5
4    3
3    1
2    1
Name: count, dtype: int64
Rating Percentage:
rating
5    50.0
4    30.0
3    10.0
2    10.0
Name: proportion, dtype: float64
Final Results:
        count  percentage
rating
5           5        50.0
4           3        30.0
3           1        10.0
2           1        10.0

### Question 10 (Intermediate) - drop_duplicates()

You have customer transaction data with duplicate entries. Remove duplicate rows, keeping only the first occurrence of each unique customer.

In [35]:
transactions = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Diana', 'Alice'],
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Keyboard', 'Laptop', 'Mouse'],
    'amount': [1200, 25, 75, 400, 75, 1200, 30]
})
transactions

  customer   product  amount
0    Alice    Laptop    1200
1      Bob     Mouse      25
2    Alice  Keyboard      75
3  Charlie   Monitor     400
4      Bob  Keyboard      75
5    Diana    Laptop    1200
6    Alice     Mouse      30

In [37]:
transactions.drop_duplicates('customer', keep='first')

  customer  product  amount
0    Alice   Laptop    1200
1      Bob    Mouse      25
3  Charlie  Monitor     400
5    Diana   Laptop    1200

## Pandas Practice Exercises - More Methods (Part 3)

### Question 1 (Beginner) - rename() columns

You have a DataFrame with abbreviated column names. Rename them to more descriptive names: 'qty' to 'quantity', 'amt' to 'amount', and 'prod' to 'product'

In [7]:
import pandas as pd

orders = pd.DataFrame({
    'id': [101, 102, 103, 104],
    'prod': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'qty': [2, 5, 3, 1],
    'amt': [2400, 125, 225, 400]
})
orders

    id      prod  qty   amt
0  101    Laptop    2  2400
1  102     Mouse    5   125
2  103  Keyboard    3   225
3  104   Monitor    1   400

In [9]:
orders = orders.rename(columns={
    'prod' : 'Product',
    'qty': 'Quantity',
    'amt':'Amount'
})
print(orders)

    id   Product  Quantity  Amount
0  101    Laptop         2    2400
1  102     Mouse         5     125
2  103  Keyboard         3     225
3  104   Monitor         1     400


### Question 2 (Beginner) - replace() values

You have product data where the category 'Tech' should be changed to 'Technology' and 'Access' should be changed to 'Accessories'. Replace these values.

In [10]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'category': ['Tech', 'Access', 'Tech', 'Access', 'Tech'],
    'price': [1200, 25, 400, 75, 80]
})

In [13]:
products.replace({
    'Tech' : 'Technology',
    'Access' : 'Accessories'
})

    product     category  price
0    Laptop   Technology   1200
1     Mouse  Accessories     25
2   Monitor   Technology    400
3  Keyboard  Accessories     75
4    Webcam   Technology     80

 ### Question 3 (Beginner) - reset_index()

You have a DataFrame that was filtered and sorted, leaving a messy index. Reset the index to a clean sequential order (0, 1, 2, 3...).

In [17]:
employees = pd.DataFrame({
    'name': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom', 'Emma'],
    'salary': [65000, 70000, 58000, 75000, 62000, 68000]
})

# Filter high earners and sort
employees = employees[employees['salary'] > 63000]
employees.sort_values('salary', ascending=False, inplace=True)
employees

    name  salary
3   Lisa   75000
1  Sarah   70000
5   Emma   68000
0   John   65000

In [20]:
employees.reset_index(drop=True)

    name  salary
0   Lisa   75000
1  Sarah   70000
2   Emma   68000
3   John   65000


### Question 4 (Intermediate) - apply() with custom function

You have temperature data in Celsius. Create a custom function to convert to Fahrenheit and apply it to the temperature column. Formula: F = (C × 9/5) + 32

In [21]:
weather = pd.DataFrame({
    'city': ['New York', 'London', 'Tokyo', 'Sydney'],
    'temp_celsius': [20, 15, 25, 18]
})
weather

       city  temp_celsius
0  New York            20
1    London            15
2     Tokyo            25
3    Sydney            18

In [28]:
weather['temp_f'] = weather['temp_celsius'].apply(lambda x : (x * (9/5)) + 32 )
weather

       city  temp_celsius  temp_f
0  New York            20    68.0
1    London            15    59.0
2     Tokyo            25    77.0
3    Sydney            18    64.4

### Apply to entire dataframe (row-wise)

In [29]:
def classify_temp(row):
    if row['temp_celsius'] > 20:
        return 'Hot'
    else:
        return 'Cold'
    
weather['Classification'] = weather.apply(classify_temp, axis=1)
weather

       city  temp_celsius  temp_f Classification
0  New York            20    68.0           Cold
1    London            15    59.0           Cold
2     Tokyo            25    77.0            Hot
3    Sydney            18    64.4           Cold

### Question 5 (Beginner) - isin() for filtering

You have sales data for many products. Filter to show only sales for 'Laptop', 'Monitor', and 'Keyboard'

In [30]:
sales = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam', 'Laptop', 'USB Cable', 'Monitor'],
    'amount': [1200, 25, 400, 75, 80, 1100, 15, 420],
    'customer': ['Alice', 'Bob', 'Charlie', 'Alice', 'Diana', 'Eve', 'Bob', 'Alice']
})

sales

     product  amount customer
0     Laptop    1200    Alice
1      Mouse      25      Bob
2    Monitor     400  Charlie
3   Keyboard      75    Alice
4     Webcam      80    Diana
5     Laptop    1100      Eve
6  USB Cable      15      Bob
7    Monitor     420    Alice

In [38]:
sales[sales['product'].isin(['Laptop','Mouse','Monitor'])]

   product  amount customer
0   Laptop    1200    Alice
1    Mouse      25      Bob
2  Monitor     400  Charlie
5   Laptop    1100      Eve
7  Monitor     420    Alice

### Question 6 (Intermediate) - String methods with .str

You have customer data with messy email addresses (mixed case, spaces). Clean them by converting to lowercase and removing spaces.

In [67]:
customers = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'email': ['ALICE@Email.COM', ' bob@email.com ', 'Charlie@EMAIL.com', 'DIANA@email.com  ']
})

print("Original Data:")
print(customers)

print('\n\nIssues in emails:')

for i , email in enumerate(customers['email']):
    print(f'Row{i}:      " {email} "     Length: {len(email)}')

print("\nCleaned Data:")
customers['Cleaned_email'] = customers['email'].str.strip().str.lower()
print(customers)

print('\n\nCleaned DataSet:')
customers['Domain'] = customers['Cleaned_email'].str.split('@').str[1]
print(customers)

Original Data:
      name              email
0    Alice    ALICE@Email.COM
1      Bob     bob@email.com
2  Charlie  Charlie@EMAIL.com
3    Diana  DIANA@email.com


Issues in emails:
Row0:      " ALICE@Email.COM "     Length: 15
Row1:      "  bob@email.com  "     Length: 15
Row2:      " Charlie@EMAIL.com "     Length: 17
Row3:      " DIANA@email.com   "     Length: 17

Cleaned Data:
      name              email      Cleaned_email
0    Alice    ALICE@Email.COM    alice@email.com
1      Bob     bob@email.com       bob@email.com
2  Charlie  Charlie@EMAIL.com  charlie@email.com
3    Diana  DIANA@email.com      diana@email.com


Cleaned DataSet:
      name              email      Cleaned_email     Domain
0    Alice    ALICE@Email.COM    alice@email.com  email.com
1      Bob     bob@email.com       bob@email.com  email.com
2  Charlie  Charlie@EMAIL.com  charlie@email.com  email.com
3    Diana  DIANA@email.com      diana@email.com  email.com

### Question 7 (Beginner) - describe() for summary statistics

You have test scores for students. Generate comprehensive summary statistics including count, mean, standard deviation, min, max, and quartiles.

In [72]:
scores = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry'],
    'math': [85, 78, 92, 88, 95, 72, 90, 83],
    'science': [90, 82, 88, 91, 89, 75, 93, 86],
    'english': [88, 85, 90, 87, 91, 80, 89, 84]
})

print('Comprehensivee Summary of test Score')
summary_scores = scores.describe().T
print(summary_scores)

Comprehensivee Summary of test Score
         count    mean       std   min    25%   50%    75%   max
math       8.0  85.375  7.595817  72.0  81.75  86.5  90.50  95.0
science    8.0  86.750  5.800246  75.0  85.00  88.5  90.25  93.0
english    8.0  86.750  3.615443  80.0  84.75  87.5  89.25  91.0

### Question 8 (Intermediate) - concat() to combine DataFrames

You have sales data from two different quarters stored in separate DataFrames. Combine them vertically (stack them) into one DataFrame.

In [78]:
q1_sales = pd.DataFrame({
    'month': ['Jan', 'Feb', 'Mar'],
    'sales': [15000, 18000, 16000],
    'expenses': [8000, 9000, 8500]
})

q2_sales = pd.DataFrame({
    'month': ['Apr', 'May', 'Jun'],
    'sales': [19000, 21000, 20000],
    'expenses': [9500, 10000, 9800]
})

print("First DataFrame")
print(q1_sales)

print('\nSecond DataFrame')
print(q2_sales)


df = pd.concat([q1_sales, q2_sales])
df.reset_index(drop=True,inplace=True)

print('\n\n Combined DataFrame with new index:')
print(df)

First DataFrame
  month  sales  expenses
0   Jan  15000      8000
1   Feb  18000      9000
2   Mar  16000      8500

Second DataFrame
  month  sales  expenses
0   Apr  19000      9500
1   May  21000     10000
2   Jun  20000      9800


 Combined DataFrame with new index:
  month  sales  expenses
0   Jan  15000      8000
1   Feb  18000      9000
2   Mar  16000      8500
3   Apr  19000      9500
4   May  21000     10000
5   Jun  20000      9800

### Question 9 (Intermediate) - merge() to join DataFrames

You have customer information in one DataFrame and their orders in another. Merge them to see customer names alongside their orders

In [106]:
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'city': ['NYC', 'LA', 'Chicago', 'Boston']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 2],
    'product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'amount': [1200, 25, 400, 75, 80]
})

print('Customer DataFrame:\n')
print(customers)

print('\n Customer Orders DataFrame:\n')
print(orders)

merge_df = pd.merge(customers,orders, on='customer_id', how='left')

print('\n\nMerged DataSet of both dataframes\n')
print(merge_df)
print('\n\n')


print('\nfinal dataset:\n')
summary_df = (
    merge_df.groupby('name')
    .agg({'product': 'count', 'amount': 'sum'})
    .rename(columns={'product': 'count', 'amount': 'spent'})
    .reset_index()
)
print(summary_df)

Customer DataFrame:

   customer_id     name     city
0            1    Alice      NYC
1            2      Bob       LA
2            3  Charlie  Chicago
3            4    Diana   Boston

 Customer Orders DataFrame:

   order_id  customer_id   product  amount
0       101            1    Laptop    1200
1       102            2     Mouse      25
2       103            1   Monitor     400
3       104            3  Keyboard      75
4       105            2    Webcam      80


Merged DataSet of both dataframes

   customer_id     name     city  order_id   product  amount
0            1    Alice      NYC     101.0    Laptop  1200.0
1            1    Alice      NYC     103.0   Monitor   400.0
2            2      Bob       LA     102.0     Mouse    25.0
3            2      Bob       LA     105.0    Webcam    80.0
4            3  Charlie  Chicago     104.0  Keyboard    75.0
5            4    Diana   Boston       NaN       NaN     NaN




final dataset:

      name  count   spent
0    Alice      2  1600.0
1      Bob      2   105.0
2  Charlie      1    75.0
3    Diana      0     0.0

### Question 10 (Intermediate) - pivot_table() for reshaping data

You have sales data in long format (one row per transaction). Create a pivot table showing total sales for each salesperson by region.

In [117]:
sales = pd.DataFrame({
    'salesperson': ['Tom', 'Jerry', 'Tom', 'Spike', 'Jerry', 'Tom', 'Spike', 'Jerry'],
    'region': ['North', 'South', 'South', 'North', 'North', 'North', 'South', 'South'],
    'product': ['A', 'B', 'A', 'C', 'C', 'B', 'A', 'A'],
    'sales': [150, 200, 180, 120, 250, 170, 90, 220]
})


sales_pivot = pd.pivot_table(
    sales,
    values='sales',
    columns='region',
    index='salesperson',
    aggfunc='sum',
    fill_value=0,
    margins=True # add grand total
)


print('Sales Transaction Data:\n', sales)
print('\nSales Pivot Table:\n',sales_pivot)

Sales Transaction Data:
   salesperson region product  sales
0         Tom  North       A    150
1       Jerry  South       B    200
2         Tom  South       A    180
3       Spike  North       C    120
4       Jerry  North       C    250
5         Tom  North       B    170
6       Spike  South       A     90
7       Jerry  South       A    220

Sales Pivot Table:
 region       North  South   All
salesperson
Jerry          250    420   670
Spike          120     90   210
Tom            320    180   500
All            690    690  1380