In [2]:
import pandas as pd

### Question 1 (Beginner) - loc[] for label-based selection

You have a DataFrame of students with their test scores. Use loc[] to select the data for students 'Alice' and 'Charlie', showing only their 'math_score' and 'science_score' columns.

In [3]:
import pandas as pd

students = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'math_score': [85, 78, 92, 88, 95],
    'science_score': [90, 82, 88, 91, 89],
    'english_score': [88, 85, 90, 87, 91]
})
students.set_index('name', inplace=True)
students

         math_score  science_score  english_score
name
Alice            85             90             88
Bob              78             82             85
Charlie          92             88             90
Diana            88             91             87
Eve              95             89             91

In [5]:
students.loc[['Alice','Charlie'],['math_score','english_score']]

         math_score  english_score
name
Alice            85             88
Charlie          92             90

### Question 2 (Beginner) - iloc[] for position-based selection

Using the same students DataFrame, select the first 3 rows and the last 2 columns using position-based indexing.

In [16]:
students.iloc[:2,1:]

       science_score  english_score
name
Alice             90             88
Bob               82             85

### Question 3 (Beginner) - sort_values()

You have employee data. Sort the employees by salary in descending order (highest to lowest).

In [17]:
employees = pd.DataFrame({
    'name': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom'],
    'department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'salary': [65000, 70000, 58000, 75000, 62000],
    'age': [28, 34, 45, 29, 38]
})
employees

    name department  salary  age
0   John         IT   65000   28
1  Sarah         HR   70000   34
2   Mike         IT   58000   45
3   Lisa    Finance   75000   29
4    Tom         HR   62000   38

In [25]:
employees.sort_values('salary', ascending=False)

    name department  salary  age
3   Lisa    Finance   75000   29
1  Sarah         HR   70000   34
0   John         IT   65000   28
4    Tom         HR   62000   38
2   Mike         IT   58000   45

In [24]:
employees[employees.duplicated('department',keep='last')]

    name department  salary  age
0   John         IT   65000   28
1  Sarah         HR   70000   34

### Question 4 (Intermediate) - sort_values() with multiple columns

You have sales data. Sort first by 'region' (alphabetically), then by 'sales' (highest to lowest) within each region.

In [26]:
sales = pd.DataFrame({
    'salesperson': ['Tom', 'Jerry', 'Mike', 'Sarah', 'Lisa', 'John'],
    'region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'sales': [15000, 22000, 18000, 19000, 21000, 17000]
})
sales

  salesperson region  sales
0         Tom   East  15000
1       Jerry   West  22000
2        Mike   East  18000
3       Sarah   West  19000
4        Lisa   East  21000
5        John   West  17000

In [32]:
sales_region = sales.sort_values('region')
print(sales_region)

sales_region.sort_values('sales', ascending=False)

  salesperson region  sales
0         Tom   East  15000
2        Mike   East  18000
4        Lisa   East  21000
1       Jerry   West  22000
3       Sarah   West  19000
5        John   West  17000

  salesperson region  sales
1       Jerry   West  22000
4        Lisa   East  21000
3       Sarah   West  19000
2        Mike   East  18000
5        John   West  17000
0         Tom   East  15000

### Question 5 (Beginner) - Boolean filtering

You have product data. Filter and show only products that are priced above $100.

In [3]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'USB Cable', 'Headphones'],
    'price': [1200, 25, 75, 400, 15, 150],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories'],
    'in_stock': [True, True, False, True, True, False]
})
products

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
1       Mouse     25  Accessories      True
2    Keyboard     75  Accessories     False
3     Monitor    400  Electronics      True
4   USB Cable     15  Accessories      True
5  Headphones    150  Accessories     False

In [39]:
products[products['price']>100]

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
3     Monitor    400  Electronics      True
5  Headphones    150  Accessories     False

### Question 6 (Intermediate) - Multiple conditions with boolean filtering

From the products DataFrame, find all products that are:

    In the 'Accessories' category AND
    
    Priced between $50 and $200 (inclusive) AND
    
    Currently in stock

In [4]:
products = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'USB Cable', 'Headphones', 'Webcam'],
    'price': [1200, 25, 75, 400, 15, 150, 80],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Accessories'],
    'in_stock': [True, True, False, True, True, True, True]
})

products

      product  price     category  in_stock
0      Laptop   1200  Electronics      True
1       Mouse     25  Accessories      True
2    Keyboard     75  Accessories     False
3     Monitor    400  Electronics      True
4   USB Cable     15  Accessories      True
5  Headphones    150  Accessories      True
6      Webcam     80  Accessories      True

In [10]:
products[
    (products['category'] == 'Accessories') &
    (products['price'] > 50) &
    (products['price'] < 200) &
    (products['in_stock'] == True)
]

      product  price     category  in_stock
5  Headphones    150  Accessories      True
6      Webcam     80  Accessories      True

### Question 7 (Beginner) - fillna() to handle missing data

You have temperature readings with some missing values (NaN). Fill the missing values with the average temperature.

In [12]:
import numpy as np

temperatures = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami'],
    'temperature': [72, np.nan, 65, np.nan, 88, 82]
})
temperatures

          city  temperature
0     New York         72.0
1  Los Angeles          NaN
2      Chicago         65.0
3      Houston          NaN
4      Phoenix         88.0
5        Miami         82.0

In [13]:
avg_tmep =temperatures['temperature'].mean()
temperatures.fillna(avg_tmep)

          city  temperature
0     New York        72.00
1  Los Angeles        76.75
2      Chicago        65.00
3      Houston        76.75
4      Phoenix        88.00
5        Miami        82.00

### Question 8 (Beginner) - Creating new columns

You have sales data with quantity and unit price. Create a new column 'total_price' that calculates quantity × unit_price.

In [19]:
sales = pd.DataFrame({
    'product': ['Widget', 'Gadget', 'Doohickey', 'Thingamajig'],
    'quantity': [10, 5, 8, 12],
    'unit_price': [25.50, 40.00, 15.75, 30.00]
})

sales

       product  quantity  unit_price
0       Widget        10       25.50
1       Gadget         5       40.00
2    Doohickey         8       15.75
3  Thingamajig        12       30.00

In [21]:
sales['Total_price'] = sales['quantity'] * sales['unit_price']
sales

       product  quantity  unit_price  Total_price
0       Widget        10       25.50        255.0
1       Gadget         5       40.00        200.0
2    Doohickey         8       15.75        126.0
3  Thingamajig        12       30.00        360.0

### Question 9 (Intermediate) - value_counts()

You have customer feedback data. Count how many times each rating appears, show the results in descending order with percentages.

In [23]:
feedback = pd.DataFrame({
    'customer': ['John', 'Sarah', 'Mike', 'Lisa', 'Tom', 'Emma', 'David', 'Anna', 'Chris', 'Julie'],
    'rating': [5, 4, 5, 3, 5, 4, 5, 2, 4, 5]
})
feedback

  customer  rating
0     John       5
1    Sarah       4
2     Mike       5
3     Lisa       3
4      Tom       5
5     Emma       4
6    David       5
7     Anna       2
8    Chris       4
9    Julie       5

In [34]:
print('Rating count:')
rating_count = feedback.value_counts('rating')
print(rating_count)

print('Rating Percentage:')

rating_percentage = feedback.value_counts('rating',normalize=True) * 100

print(rating_percentage)

print('Final Results:')
final_result = pd.DataFrame({
    'count' : rating_count,\
    'percentage': rating_percentage
})
print(final_result)

Rating count:
rating
5    5
4    3
3    1
2    1
Name: count, dtype: int64
Rating Percentage:
rating
5    50.0
4    30.0
3    10.0
2    10.0
Name: proportion, dtype: float64
Final Results:
        count  percentage
rating
5           5        50.0
4           3        30.0
3           1        10.0
2           1        10.0

### Question 10 (Intermediate) - drop_duplicates()

You have customer transaction data with duplicate entries. Remove duplicate rows, keeping only the first occurrence of each unique customer.

In [35]:
transactions = pd.DataFrame({
    'customer': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Diana', 'Alice'],
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Keyboard', 'Laptop', 'Mouse'],
    'amount': [1200, 25, 75, 400, 75, 1200, 30]
})
transactions

  customer   product  amount
0    Alice    Laptop    1200
1      Bob     Mouse      25
2    Alice  Keyboard      75
3  Charlie   Monitor     400
4      Bob  Keyboard      75
5    Diana    Laptop    1200
6    Alice     Mouse      30

In [37]:
transactions.drop_duplicates('customer', keep='first')

  customer  product  amount
0    Alice   Laptop    1200
1      Bob    Mouse      25
3  Charlie  Monitor     400
5    Diana   Laptop    1200