### Practice Exercise: Drop & sample method

#### Question 1: 
You have a DataFrame with employee data. Remove the employee named "John Smith" from the DataFrame using the drop() method with the axis parameter.

In [2]:
import pandas as pd

In [11]:
employees = pd.DataFrame({
    'name': ['John Smith', 'Sarah Jones', 'Mike Brown', 'Lisa White'],
    'salary': [50000, 60000, 55000, 65000],
    'department': ['IT', 'HR', 'IT', 'Finance']
})
employees.set_index(['name'],inplace=True)
employees

             salary department
name
John Smith    50000         IT
Sarah Jones   60000         HR
Mike Brown    55000         IT
Lisa White    65000    Finance

In [13]:
#1 
employees.drop('John Smith',axis=0)

             salary department
name
Sarah Jones   60000         HR
Mike Brown    55000         IT
Lisa White    65000    Finance

#### Question2: 
Using the same employee DataFrame, remove the "department" column using the columns parameter instead of the axis parameter.

In [16]:
employees.drop(['department'],axis=1)

             salary
name
John Smith    50000
Sarah Jones   60000
Mike Brown    55000
Lisa White    65000

#### Question4: 
Create a DataFrame of 5 students with their scores. Remove the last column by its position (index), not by name.

In [18]:
students = pd.DataFrame({
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'math_score': [85, 90, 78, 92, 88],
    'english_score': [88, 85, 90, 87, 91]
})
students

   student_id     name  math_score  english_score
0         101    Alice          85             88
1         102      Bob          90             85
2         103  Charlie          78             90
3         104    Diana          92             87
4         105      Eve          88             91

In [29]:
students.drop(students.columns[[-1]],axis=1)

   student_id     name  math_score
0         101    Alice          85
1         102      Bob          90
2         103  Charlie          78
3         104    Diana          92
4         105      Eve          88

#### Question 4: 
You have a products DataFrame. Remove multiple rows (products with IDs 'P001' and 'P003') and make the change permanent using inplace=True.

In [32]:
products = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'product_name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'price': [1200, 25, 75, 300, 80],
    'stock': [15, 100, 50, 30, 45]
})
products.set_index('product_id',inplace=True)
products

           product_name  price  stock
product_id
P001             Laptop   1200     15
P002              Mouse     25    100
P003           Keyboard     75     50
P004            Monitor    300     30
P005             Webcam     80     45

In [33]:
products.drop(index=['P001','P003'],axis=0)

           product_name  price  stock
product_id
P002              Mouse     25    100
P004            Monitor    300     30
P005             Webcam     80     45

#### Question5:
Given a sales DataFrame, drop multiple columns ('sales_person' and 'region') at once and keep the result without using inplace=True.

In [34]:
sales = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'sales_person': ['Tom', 'Jerry', 'Tom', 'Spike'],
    'region': ['North', 'South', 'East', 'West'],
    'amount': [1500, 2000, 1800, 2200],
    'date': ['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18']
})
sales

   order_id sales_person region  amount        date
0         1          Tom  North    1500  2024-01-15
1         2        Jerry  South    2000  2024-01-16
2         3          Tom   East    1800  2024-01-17
3         4        Spike   West    2200  2024-01-18

In [35]:
sales.drop(columns=['sales_person','region'],axis=1)

   order_id  amount        date
0         1    1500  2024-01-15
1         2    2000  2024-01-16
2         3    1800  2024-01-17
3         4    2200  2024-01-18

#### Question6: 
You have a DataFrame of movies. Use the sample() method to randomly select 3 movie titles. Make sure your results are reproducible by setting a random_state.

In [37]:
movies = pd.DataFrame({
    'title': ['Inception', 'The Matrix', 'Interstellar', 'The Prestige', 
              'Memento', 'Tenet', 'Dunkirk', 'The Dark Knight'],
    'year': [2010, 1999, 2014, 2006, 2000, 2020, 2017, 2008],
    'rating': [8.8, 8.7, 8.6, 8.5, 8.4, 7.5, 7.9, 9.0]
})
movies

             title  year  rating
0        Inception  2010     8.8
1       The Matrix  1999     8.7
2     Interstellar  2014     8.6
3     The Prestige  2006     8.5
4          Memento  2000     8.4
5            Tenet  2020     7.5
6          Dunkirk  2017     7.9
7  The Dark Knight  2008     9.0

In [41]:
movies.sample(3,random_state=1)

             title  year  rating
7  The Dark Knight  2008     9.0
2     Interstellar  2014     8.6
1       The Matrix  1999     8.7

#### Question7:
Create a DataFrame of countries with populations. Drop the first and third rows using their index positions (not names), and also drop the last column by position.

In [42]:
countries = pd.DataFrame({
    'country': ['USA', 'China', 'India', 'Brazil', 'Russia'],
    'population': [331, 1441, 1393, 213, 146],
    'area': [9834, 9597, 3287, 8516, 17098],
    'gdp': [21.43, 14.34, 2.87, 1.84, 1.70]
})
countries

  country  population   area    gdp
0     USA         331   9834  21.43
1   China        1441   9597  14.34
2   India        1393   3287   2.87
3  Brazil         213   8516   1.84
4  Russia         146  17098   1.70

In [49]:
df_1 = countries.drop(countries.index[[0,2]],axis=0)

df_final = df_1.drop(countries.columns[[-1]],axis=1)
df_final

  country  population   area
1   China        1441   9597
3  Brazil         213   8516
4  Russia         146  17098

#### Question8:
Given a books DataFrame with a custom index, sample 5 random ROWS (not just one column) and ensure reproducibility.

In [51]:
books = pd.DataFrame({
    'isbn': ['978-01', '978-02', '978-03', '978-04', '978-05', 
             '978-06', '978-07', '978-08', '978-09', '978-10'],
    'title': ['Book A', 'Book B', 'Book C', 'Book D', 'Book E',
              'Book F', 'Book G', 'Book H', 'Book I', 'Book J'],
    'author': ['Author 1', 'Author 2', 'Author 3', 'Author 1', 'Author 4',
               'Author 2', 'Author 5', 'Author 3', 'Author 6', 'Author 1'],
    'price': [19.99, 24.99, 15.99, 29.99, 22.99, 
              18.99, 27.99, 16.99, 21.99, 25.99]
})
books.set_index('isbn', inplace=True)
books

         title    author  price
isbn
978-01  Book A  Author 1  19.99
978-02  Book B  Author 2  24.99
978-03  Book C  Author 3  15.99
978-04  Book D  Author 1  29.99
978-05  Book E  Author 4  22.99
978-06  Book F  Author 2  18.99
978-07  Book G  Author 5  27.99
978-08  Book H  Author 3  16.99
978-09  Book I  Author 6  21.99
978-10  Book J  Author 1  25.99

In [52]:
books.sample(5)

         title    author  price
isbn
978-09  Book I  Author 6  21.99
978-08  Book H  Author 3  16.99
978-01  Book A  Author 1  19.99
978-06  Book F  Author 2  18.99
978-07  Book G  Author 5  27.99

#### Question9:
You have a sensors DataFrame. Drop all rows where the sensor_id starts with 'S-1' (S-10, S-11, S-12) without specifying each one individually. Use list comprehension with drop().

In [54]:
sensors = pd.DataFrame({
    'sensor_id': ['S-05', 'S-10', 'S-11', 'S-12', 'S-20', 'S-21', 'S-30'],
    'location': ['Room A', 'Room B', 'Room C', 'Room D', 'Room E', 'Room F', 'Room G'],
    'temperature': [22.5, 23.1, 21.8, 24.2, 22.0, 23.5, 21.5],
    'humidity': [45, 50, 48, 52, 46, 51, 44]
})
sensors.set_index('sensor_id', inplace=True)
sensors

          location  temperature  humidity
sensor_id
S-05        Room A         22.5        45
S-10        Room B         23.1        50
S-11        Room C         21.8        48
S-12        Room D         24.2        52
S-20        Room E         22.0        46
S-21        Room F         23.5        51
S-30        Room G         21.5        44

In [55]:
sensors.drop(['S-10','S-11','S-12'],axis=0)

          location  temperature  humidity
sensor_id
S-05        Room A         22.5        45
S-20        Room E         22.0        46
S-21        Room F         23.5        51
S-30        Room G         21.5        44

#### Question10:
You have a large dataset of transactions. First, drop the 'customer_email' and 'customer_phone' columns for privacy. Then, sample 30% of the remaining data for analysis. Finally, drop any row where transaction_id is 'TXN-005'. Chain all these operations together.

In [57]:
transactions = pd.DataFrame({
    'transaction_id': ['TXN-001', 'TXN-002', 'TXN-003', 'TXN-004', 'TXN-005',
                       'TXN-006', 'TXN-007', 'TXN-008', 'TXN-009', 'TXN-010'],
    'customer_name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve',
                      'Frank', 'Grace', 'Henry', 'Iris', 'Jack'],
    'customer_email': ['alice@x.com', 'bob@x.com', 'charlie@x.com', 'diana@x.com', 'eve@x.com',
                       'frank@x.com', 'grace@x.com', 'henry@x.com', 'iris@x.com', 'jack@x.com'],
    'customer_phone': ['111-1111', '222-2222', '333-3333', '444-4444', '555-5555',
                       '666-6666', '777-7777', '888-8888', '999-9999', '000-0000'],
    'amount': [150, 200, 175, 300, 125, 450, 275, 350, 180, 220]
})
transactions.set_index('transaction_id', inplace=True)

transactions

               customer_name customer_email customer_phone  amount
transaction_id
TXN-001                Alice    alice@x.com       111-1111     150
TXN-002                  Bob      bob@x.com       222-2222     200
TXN-003              Charlie  charlie@x.com       333-3333     175
TXN-004                Diana    diana@x.com       444-4444     300
TXN-005                  Eve      eve@x.com       555-5555     125
TXN-006                Frank    frank@x.com       666-6666     450
TXN-007                Grace    grace@x.com       777-7777     275
TXN-008                Henry    henry@x.com       888-8888     350
TXN-009                 Iris     iris@x.com       999-9999     180
TXN-010                 Jack     jack@x.com       000-0000     220

In [75]:
df_10 = (transactions.drop(columns=['customer_email','customer_phone'],axis=1).sample(frac=0.3).drop('TXN-005',axis=0, errors='ignore'))
df_10

               customer_name  amount
transaction_id
TXN-004                Diana     300
TXN-008                Henry     350